services:
  api:
    build: ./backend
    ports: ["5000:5000"]
    env_file:
      - ./backend/.env
    networks:
      - resume

  database:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - resume

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    networks:
      - resume

volumes:
  postgres-data:

networks:
  resume: